services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:80"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:80"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp