services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "8080:8080"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgre5!123
      POSTGRES_DB: chatapp