services:
 postgres:
    image: postgres:latest
    container_name: ChatPostgresDb
    environment:
      POSTGRES_HOST: postgres_container
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ChatApplicationDb

    ports:
      - '5432:5432'
    networks:
      - private
    restart: always

 chatapplication.server:
    build: ./ChatApplication.Server
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - private
    

 chatapplication.client:
    build: ./ChatApplication.Client
    ports:
      - "59996:59996"
    volumes:
     - .:/app
     - ./node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    networks:
      - public


networks:
  public:
  private: