FROM node:20-alpine AS build

WORKDIR /app

COPY chatapplication.client/ ./
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]