services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:8080"
    depends_on:
      - db

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    ports: 
      - "8080:80"
    depends_on:
      - client
      - server
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chatapp