services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: ChatApplicationDb

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ChatApplicationDb;Username=postgres;Password=mysecretpassword
    restart: "no"  # Don't restart once it's done

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "3001:8080"
    depends_on:
      - db
      - migrator
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ChatApplicationDb;Username=postgres;Password=mysecretpassword

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"

  proxy:
    build: 
      context: .
      dockerfile: Dockerfile.proxy
    ports: 
      - "8080:80"
    depends_on:
      - client
      - server
